## 7. Keras - RNN

### 1. Importing libraries

### 2. Importing data

### 3. Data wrangling

### 4. Data reshaping

### 5. Data splitting

### 6. Keras model creation

### 7. Model compiling and running

### 8. Confusion matrix

### 9. Adjusting hyperparameters and running model test 2

### 10. Adjusting hyperparameters and running model test 3

### 11. Adjusting hyperparameters and running model test 4

### 12. Adjusting hyperparameters and running model test 5

### 13. Adjusting hyperparameters and running model test 6

### 14. Adjusting hyperparameters and running model test 7

### 15. Adjusting hyperparameters and running model test 8

### 16. Adjusting hyperparameters and running model test 9

### 17. Adjusting hyperparameters and running model test 10

### 18. Adjusting hyperparameters and running model test 11

### 19 Adjusting hyperparameters and running model test 12

#### 1. Importing libraries

In [4]:
# Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import os
import operator
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from numpy import unique
from numpy import reshape
from keras.models import Sequential
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, Dropout, LSTM
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

#### 2. Importing data

In [6]:
path = r'C:\Users\Priya\OneDrive\Documents\CareerFoundry\Machine Learning'

In [7]:
path

'C:\\Users\\Priya\\OneDrive\\Documents\\CareerFoundry\\Machine Learning'

In [8]:
# Importing the ClimateWins dataset
climate = pd.read_csv(os.path.join(path, 'Achievement 1', 'Data Sets', 'Dataset-weather-prediction-dataset-processed.csv'), index_col = False)

In [9]:
# Checking the shape of the dataframe
climate.shape

(22950, 170)

In [10]:
# Viewing the first five rows of the dataframe
climate.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [11]:
# Importing the pleasant weather dataset
pleasantweather = pd.read_csv(os.path.join(path, 'Achievement 1', 'Data Sets', 'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'), index_col = False)

In [12]:
# Checking the shape of the pleasantweather dataset
pleasantweather.shape

(22950, 16)

In [13]:
# Viewing the first five rows of the pleasant weather dataset
pleasantweather.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

#### 3. Data wrangling

In [15]:
# Removing the limit on the number of rows that can be shown
pd.options.display.max_rows = None

In [16]:
# Checking the columns in the climate dataset
list(climate)

['DATE',
 'MONTH',
 'BASEL_cloud_cover',
 'BASEL_wind_speed',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_snow_depth',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_wind_speed',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_snow_depth',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'GDANSK_cloud_cover',
 'GDANSK_humidity',
 'GDANSK_precipitation',
 'GDANSK_snow_depth',
 'GDANSK_temp_mean',
 'GDANSK_temp_min',
 'GDANSK_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_snow_depth',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_wind_speed',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_wind_speed',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_wind_speed',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_wind_speed',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_snow_depth',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_wind_speed',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_snow_depth',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'ROMA_cloud_cover',
 'ROMA_wind_speed',
 'ROMA_humidity',
 'ROMA_pressure',
 'ROMA_sunshine',
 'ROMA_temp_mean',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_wind_speed',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'TOURS_wind_speed',
 'TOURS_humidity',
 'TOURS_pressure',
 'TOURS_global_radiation',
 'TOURS_precipitation',
 'TOURS_temp_mean',
 'TOURS_temp_min',
 'TOURS_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_snow_depth',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [17]:
# Dropping the DATE and MONTH columns from the climate dataframe
climate = climate.drop(['DATE', 'MONTH'], axis=1)

In [18]:
# Dropping all the columns for Gdansk, Roma, and Tours from the climate dataframe to match the pleasantweather dataframe
climate = climate.drop(['GDANSK_cloud_cover', 'GDANSK_humidity', 'GDANSK_precipitation', 'GDANSK_snow_depth', 'GDANSK_temp_mean', 'GDANSK_temp_min',
'GDANSK_temp_max', 'ROMA_cloud_cover', 'ROMA_wind_speed', 'ROMA_humidity', 'ROMA_pressure', 'ROMA_sunshine', 'ROMA_temp_mean', 'TOURS_wind_speed',
'TOURS_humidity', 'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation', 'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'], axis=1)

In [19]:
# Checking if the columns for Gdansk, Roma, and Tours and the DATE and MONTH columns were dropped
list(climate)

['BASEL_cloud_cover',
 'BASEL_wind_speed',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_snow_depth',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_wind_speed',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_wind_speed',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_snow_depth',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_snow_depth',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_wind_speed',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_wind_speed',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_wind_speed',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_wind_speed',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_snow_depth',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_wind_speed',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_snow_depth',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_wind_speed',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_snow_depth',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [20]:
# Checking the shape of the climate dataframe
climate.shape

(22950, 147)

In [21]:
# Dropping the DATE column from the pleasantweather dataframe
pleasantweather = pleasantweather.drop(['DATE'], axis=1)

In [22]:
# Checking the shape of the pleasantweather dataframe
pleasantweather.shape

(22950, 15)

In [23]:
# Viewing the first five rows of the pleasantweather dataframe
pleasantweather.head()

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [24]:
# Creating observation_types with the different observation types
observation_types = ['cloud_cover', 'wind_speed', 'humidity', 'pressure', 'global_radiation', 'precipitation', 'snow_depth', 'sunshine', 'temp_mean',
'temp_min', 'temp_max']

In [26]:
# Creating station_counts to store the count of stations for each observation type
station_counts = {}

for obs in observation_types:
    # Selecting columns for each observation type
    columns = [col for col in climate.columns if col.endswith(obs)]
    
    # Creating a count for the number of stations that have each observation type
    station_counts[obs] = len(columns)

In [27]:
# Printing the count of stations that each observation type has
print("Count of stations for each observation type:")
for obs, count in station_counts.items():
    print(f"{obs}: {count} stations")

Count of stations for each observation type:
cloud_cover: 14 stations
wind_speed: 9 stations
humidity: 14 stations
pressure: 14 stations
global_radiation: 15 stations
precipitation: 15 stations
snow_depth: 6 stations
sunshine: 15 stations
temp_mean: 15 stations
temp_min: 15 stations
temp_max: 15 stations

In [28]:
# Creating cols_to_drop with all columns for wind_speed and snow_depth
cols_to_drop = [col for col in climate.columns if col.endswith(('wind_speed', 'snow_depth'))]

In [29]:
# Dropping all columns for wind_speed and snow_depth since most stations do not have these columns
climate = climate.drop(cols_to_drop, axis=1)

In [30]:
# Checking if the columns for wind_speed and snow_depth were dropped
list(climate)

['BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [31]:
# Checking the shape of the climate dataframe
climate.shape

(22950, 132)

In [32]:
# Creating a list of weather stations
weather_stations = ['BASEL', 'BELGRADE', 'BUDAPEST', 'DEBILT', 'DUSSELDORF', 'HEATHROW', 'KASSEL', 'LJUBLJANA', 'MAASTRICHT', 'MADRID', 'MUNCHENB',
'OSLO', 'SONNBLICK', 'STOCKHOLM', 'VALENTIA']

In [33]:
# Converting weather_stations to a set from a list
weather_stations = set(weather_stations)

In [34]:
# Creating missing_observations with the three observation types that are missing
missing_observations = ['cloud_cover', 'humidity', 'pressure']

In [35]:
# Creating missing_stations_observations to store the stations with the missing observations
missing_stations_observations = {}

for obs in missing_observations:
    # Selecting columns for each observation type
    columns = [col for col in climate.columns if col.endswith(obs)]
    
    # Removing the observation type from the column names to obtain station names
    station_names = set([col.replace(f'_{obs}', '') for col in columns])
    
    # Identifying stations that are missing
    missing_stations_observations[obs] = weather_stations - station_names

    # Creating missing stations
    missing_stations = missing_stations_observations[obs]

In [36]:
# Printing the station names that are missing for the three observations
for obs, missing_stations in missing_stations_observations.items():
    print(f"\nStation missing from {obs}:")
    if missing_stations:
        for station in missing_stations:
            print(station)
    else: print("None")

Station missing from cloud_cover:
KASSEL

Station missing from humidity:
STOCKHOLM

Station missing from pressure:
MUNCHENB

In [68]:
# Finding the column number of the HEATHROW_temp_max column to insert the new KASSEL_cloud_cover column next to it
climate.columns.get_loc('HEATHROW_temp_max')

53

In [70]:
# Creating and inserting the KASSEL_cloud_cover column at position 54 by copying the DUSSELDORF_cloud_cover column
climate.insert(54, 'KASSEL_cloud_cover', climate['DUSSELDORF_cloud_cover'])

In [72]:
# Finding the location of the STOCKHOLM_cloud_cover column to insert the new STOCKHOLM_humidity column next to it
climate.columns.get_loc('STOCKHOLM_cloud_cover')

116

In [74]:
# Creating and inserting the STOCKHOLM_humidity column at position 117 by copying the OSLO_humidity column
climate.insert(117, 'STOCKHOLM_humidity', climate['OSLO_humidity'])

In [76]:
# Finding the location of the MUNCHENB_humidity column to insert the new MUNCHENB_pressure column next to it
climate.columns.get_loc('MUNCHENB_humidity')

91

In [78]:
# Creating and inserting the MUNCHENB_pressure column at position 92 by copying the SONNBLICK_pressure column
climate.insert(92, 'MUNCHENB_pressure', climate['SONNBLICK_pressure'])

In [80]:
# Checking if the KASSEL_cloud_cover, STOCKHOLM_humidity, MUNCHENB_pressure columns were added in the right positions
list(climate)

['BASEL_cloud_cover',
 'BASEL_humidity',
 'BASEL_pressure',
 'BASEL_global_radiation',
 'BASEL_precipitation',
 'BASEL_sunshine',
 'BASEL_temp_mean',
 'BASEL_temp_min',
 'BASEL_temp_max',
 'BELGRADE_cloud_cover',
 'BELGRADE_humidity',
 'BELGRADE_pressure',
 'BELGRADE_global_radiation',
 'BELGRADE_precipitation',
 'BELGRADE_sunshine',
 'BELGRADE_temp_mean',
 'BELGRADE_temp_min',
 'BELGRADE_temp_max',
 'BUDAPEST_cloud_cover',
 'BUDAPEST_humidity',
 'BUDAPEST_pressure',
 'BUDAPEST_global_radiation',
 'BUDAPEST_precipitation',
 'BUDAPEST_sunshine',
 'BUDAPEST_temp_mean',
 'BUDAPEST_temp_min',
 'BUDAPEST_temp_max',
 'DEBILT_cloud_cover',
 'DEBILT_humidity',
 'DEBILT_pressure',
 'DEBILT_global_radiation',
 'DEBILT_precipitation',
 'DEBILT_sunshine',
 'DEBILT_temp_mean',
 'DEBILT_temp_min',
 'DEBILT_temp_max',
 'DUSSELDORF_cloud_cover',
 'DUSSELDORF_humidity',
 'DUSSELDORF_pressure',
 'DUSSELDORF_global_radiation',
 'DUSSELDORF_precipitation',
 'DUSSELDORF_sunshine',
 'DUSSELDORF_temp_mean',
 'DUSSELDORF_temp_min',
 'DUSSELDORF_temp_max',
 'HEATHROW_cloud_cover',
 'HEATHROW_humidity',
 'HEATHROW_pressure',
 'HEATHROW_global_radiation',
 'HEATHROW_precipitation',
 'HEATHROW_sunshine',
 'HEATHROW_temp_mean',
 'HEATHROW_temp_min',
 'HEATHROW_temp_max',
 'KASSEL_cloud_cover',
 'KASSEL_humidity',
 'KASSEL_pressure',
 'KASSEL_global_radiation',
 'KASSEL_precipitation',
 'KASSEL_sunshine',
 'KASSEL_temp_mean',
 'KASSEL_temp_min',
 'KASSEL_temp_max',
 'LJUBLJANA_cloud_cover',
 'LJUBLJANA_humidity',
 'LJUBLJANA_pressure',
 'LJUBLJANA_global_radiation',
 'LJUBLJANA_precipitation',
 'LJUBLJANA_sunshine',
 'LJUBLJANA_temp_mean',
 'LJUBLJANA_temp_min',
 'LJUBLJANA_temp_max',
 'MAASTRICHT_cloud_cover',
 'MAASTRICHT_humidity',
 'MAASTRICHT_pressure',
 'MAASTRICHT_global_radiation',
 'MAASTRICHT_precipitation',
 'MAASTRICHT_sunshine',
 'MAASTRICHT_temp_mean',
 'MAASTRICHT_temp_min',
 'MAASTRICHT_temp_max',
 'MADRID_cloud_cover',
 'MADRID_humidity',
 'MADRID_pressure',
 'MADRID_global_radiation',
 'MADRID_precipitation',
 'MADRID_sunshine',
 'MADRID_temp_mean',
 'MADRID_temp_min',
 'MADRID_temp_max',
 'MUNCHENB_cloud_cover',
 'MUNCHENB_humidity',
 'MUNCHENB_pressure',
 'MUNCHENB_global_radiation',
 'MUNCHENB_precipitation',
 'MUNCHENB_sunshine',
 'MUNCHENB_temp_mean',
 'MUNCHENB_temp_min',
 'MUNCHENB_temp_max',
 'OSLO_cloud_cover',
 'OSLO_humidity',
 'OSLO_pressure',
 'OSLO_global_radiation',
 'OSLO_precipitation',
 'OSLO_sunshine',
 'OSLO_temp_mean',
 'OSLO_temp_min',
 'OSLO_temp_max',
 'SONNBLICK_cloud_cover',
 'SONNBLICK_humidity',
 'SONNBLICK_pressure',
 'SONNBLICK_global_radiation',
 'SONNBLICK_precipitation',
 'SONNBLICK_sunshine',
 'SONNBLICK_temp_mean',
 'SONNBLICK_temp_min',
 'SONNBLICK_temp_max',
 'STOCKHOLM_cloud_cover',
 'STOCKHOLM_humidity',
 'STOCKHOLM_pressure',
 'STOCKHOLM_global_radiation',
 'STOCKHOLM_precipitation',
 'STOCKHOLM_sunshine',
 'STOCKHOLM_temp_mean',
 'STOCKHOLM_temp_min',
 'STOCKHOLM_temp_max',
 'VALENTIA_cloud_cover',
 'VALENTIA_humidity',
 'VALENTIA_pressure',
 'VALENTIA_global_radiation',
 'VALENTIA_precipitation',
 'VALENTIA_sunshine',
 'VALENTIA_temp_mean',
 'VALENTIA_temp_min',
 'VALENTIA_temp_max']

In [82]:
# Checking the shape of the climate dataframe
climate.shape

(22950, 135)

In [84]:
# Exporting the wrangled climate dataframe
climate.to_csv(os.path.join(path, 'Achievement 2', 'Data Sets', 'weather_cleaned.csv'))

#### 4. Data reshaping

In [87]:
# Renaming the climate and pleasantweather dataframes to X and y, respectively
X = climate
y = pleasantweather

In [89]:
# Convert X and Y into arrays
X = np.array(X)
y = np.array(y)

In [91]:
# Viewing X
X

array([[ 7.    ,  0.85  ,  1.018 , ...,  8.5   ,  6.    , 10.9   ],
       [ 6.    ,  0.84  ,  1.018 , ...,  8.9   ,  5.6   , 12.1   ],
       [ 8.    ,  0.9   ,  1.018 , ..., 10.5   ,  8.1   , 12.9   ],
       ...,
       [ 4.    ,  0.76  ,  1.0227, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.8   ,  1.0212, ..., 10.7   ,  7.9   , 13.5   ],
       [ 5.    ,  0.84  ,  1.0193, ..., 10.7   ,  7.9   , 13.5   ]])

In [93]:
# Viewing y
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [95]:
# Reshaping X
X = X.reshape(-1,15,9)

In [97]:
# Checking if X was reshaped
X.shape

(22950, 15, 9)

In [99]:
# Checking the shape of y
y.shape

(22950, 15)

#### 5. Data splitting

In [102]:
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [104]:
# Printing the shapes of X_train, X_test, y_train, and y_test
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(17212, 15, 9) (17212, 15)
(5738, 15, 9) (5738, 15)

#### 6. Keras model creation

In [107]:
# Creating the Keras model
epochs = 20
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [109]:
# Viewing the model summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 16)             │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 15)             │           255 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,919 (7.50 KB)

 Trainable params: 1,919 (7.50 KB)

 Non-trainable params: 0 (0.00 B)

#### 7. Model compiling and running

In [112]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [114]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.0876 - loss: 9.9289 - val_accuracy: 0.0410 - val_loss: 8.5227
Epoch 2/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.2109 - loss: 9.7985 - val_accuracy: 0.2591 - val_loss: 8.7832
Epoch 3/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.2770 - loss: 9.9927 - val_accuracy: 0.3111 - val_loss: 9.0706
Epoch 4/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2820 - loss: 10.2302 - val_accuracy: 0.3069 - val_loss: 9.4255
Epoch 5/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.2896 - loss: 10.4463 - val_accuracy: 0.3095 - val_loss: 9.7472
Epoch 6/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.3340 - loss: 10.7602 - val_accuracy: 0.3095 - val_loss: 10.1579
Epoch 7/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.4108 - loss: 11.0649 - val_accuracy: 0.6340 - val_loss: 10.4031
Epoch 8/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.4909 - loss: 11.2983 - val_accuracy: 0.6403 - val_loss: 10.7172
Epoch 9/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.5564 - loss: 11.4654 - val_accuracy: 0.6427 - val_loss: 10.9172
Epoch 10/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5792 - loss: 11.6746 - val_accuracy: 0.6415 - val_loss: 11.1613
Epoch 11/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6034 - loss: 11.9027 - val_accuracy: 0.6424 - val_loss: 11.4580
Epoch 12/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6125 - loss: 12.2250 - val_accuracy: 0.6410 - val_loss: 11.7796
Epoch 13/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6265 - loss: 12.5289 - val_accuracy: 0.6417 - val_loss: 12.0374
Epoch 14/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6293 - loss: 12.7317 - val_accuracy: 0.6420 - val_loss: 12.2026
Epoch 15/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6299 - loss: 12.8246 - val_accuracy: 0.6410 - val_loss: 12.3622
Epoch 16/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6366 - loss: 13.1080 - val_accuracy: 0.6420 - val_loss: 12.6327
Epoch 17/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6376 - loss: 13.3750 - val_accuracy: 0.6410 - val_loss: 12.7601
Epoch 18/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6387 - loss: 13.4783 - val_accuracy: 0.6420 - val_loss: 12.9511
Epoch 19/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6402 - loss: 13.7240 - val_accuracy: 0.6420 - val_loss: 13.1504
Epoch 20/20
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6390 - loss: 13.8439 - val_accuracy: 0.6429 - val_loss: 13.3273

#### 8. Confusion matrix

In [118]:
# Defining a list of stations names
stations = {0: 'BASEL', 1: 'BELGRADE', 2: 'BUDAPEST', 3: 'DEBILT', 4: 'DUSSELDORF', 5: 'HEATHROW', 6: 'KASSEL', 7: 'LJUBLJANA', 8: 'MAASTRICHT',
9: 'MADRID', 10: 'MUNCHENB', 11: 'OSLO', 12: 'SONNBLICK', 13: 'STOCKHOLM', 14: 'VALENTIA'}

In [120]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [122]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BUDAPEST  MAASTRICHT  MADRID
True
BASEL        3680         1           0       1
BELGRADE     1087         0           0       5
BUDAPEST      213         0           0       1
DEBILT         82         0           0       0
DUSSELDORF     29         0           0       0
HEATHROW       81         1           0       0
KASSEL         11         0           0       0
LJUBLJANA      60         0           0       1
MAASTRICHT      9         0           0       0
MADRID        445         3           1       9
MUNCHENB        7         0           0       1
OSLO            5         0           0       0
STOCKHOLM       4         0           0       0
VALENTIA        1         0           0       0

#### 9. Adjusting hyperparameters and running model test 2

In [125]:
# Creating the Keras model
epochs = 30
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [127]:
# Viewing the model summary
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_1 (LSTM)                   │ (None, 16)             │         1,664 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 15)             │           255 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,919 (7.50 KB)

 Trainable params: 1,919 (7.50 KB)

 Non-trainable params: 0 (0.00 B)

In [129]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [131]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.0910 - loss: 10.3466 - val_accuracy: 0.0284 - val_loss: 9.1531
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2240 - loss: 10.2760 - val_accuracy: 0.2639 - val_loss: 9.0698
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.2711 - loss: 10.3333 - val_accuracy: 0.2687 - val_loss: 9.3025
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.2756 - loss: 10.5210 - val_accuracy: 0.2618 - val_loss: 9.5923
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.2812 - loss: 10.6333 - val_accuracy: 0.2658 - val_loss: 9.7834
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.3261 - loss: 10.7574 - val_accuracy: 0.2652 - val_loss: 10.0620
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.4079 - loss: 10.9894 - val_accuracy: 0.6373 - val_loss: 10.2872
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.4920 - loss: 11.1694 - val_accuracy: 0.6422 - val_loss: 10.5556
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.5510 - loss: 11.3644 - val_accuracy: 0.6417 - val_loss: 10.8554
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.5792 - loss: 11.6108 - val_accuracy: 0.6412 - val_loss: 11.0700
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6036 - loss: 11.7580 - val_accuracy: 0.6422 - val_loss: 11.2636
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6154 - loss: 11.9837 - val_accuracy: 0.6422 - val_loss: 11.4944
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6279 - loss: 12.2128 - val_accuracy: 0.6406 - val_loss: 11.7393
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6281 - loss: 12.4897 - val_accuracy: 0.6427 - val_loss: 12.0295
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6323 - loss: 12.7079 - val_accuracy: 0.6420 - val_loss: 12.2200
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.6382 - loss: 12.8840 - val_accuracy: 0.6415 - val_loss: 12.3572
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6407 - loss: 13.0981 - val_accuracy: 0.6433 - val_loss: 12.5774
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6403 - loss: 13.2598 - val_accuracy: 0.6422 - val_loss: 12.7958
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6406 - loss: 13.4675 - val_accuracy: 0.6420 - val_loss: 12.9185
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6412 - loss: 13.5509 - val_accuracy: 0.6413 - val_loss: 13.0442
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6413 - loss: 13.8290 - val_accuracy: 0.6419 - val_loss: 13.3295
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6429 - loss: 13.7902 - val_accuracy: 0.6412 - val_loss: 11.4291
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6437 - loss: 13.6364 - val_accuracy: 0.6424 - val_loss: 11.8796
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6439 - loss: 13.8927 - val_accuracy: 0.6426 - val_loss: 12.3160
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6434 - loss: 14.1354 - val_accuracy: 0.6433 - val_loss: 12.7644
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6433 - loss: 14.2613 - val_accuracy: 0.6419 - val_loss: 12.9344
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6439 - loss: 14.5572 - val_accuracy: 0.6413 - val_loss: 13.1463
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.6437 - loss: 14.5820 - val_accuracy: 0.6434 - val_loss: 13.3003
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6436 - loss: 14.7504 - val_accuracy: 0.6420 - val_loss: 13.3742
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6436 - loss: 14.8624 - val_accuracy: 0.6420 - val_loss: 13.6760

In [133]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [135]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Pred        BASEL  MADRID
True
BASEL        3680       2
BELGRADE     1092       0
BUDAPEST      214       0
DEBILT         82       0
DUSSELDORF     28       1
HEATHROW       80       2
KASSEL         11       0
LJUBLJANA      61       0
MAASTRICHT      9       0
MADRID        454       4
MUNCHENB        8       0
OSLO            5       0
STOCKHOLM       4       0
VALENTIA        1       0

#### 10. Adjusting hyperparameters and running model test 3

In [139]:
# Creating the Keras model
epochs = 30
batch_size = 16
n_hidden = 32

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [141]:
# Viewing the model summary
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_2 (LSTM)                   │ (None, 32)             │         5,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 15)             │           495 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,871 (22.93 KB)

 Trainable params: 5,871 (22.93 KB)

 Non-trainable params: 0 (0.00 B)

In [143]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [145]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.1796 - loss: 10.9913 - val_accuracy: 0.2797 - val_loss: 9.4641
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2775 - loss: 11.1998 - val_accuracy: 0.2668 - val_loss: 9.8850
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2880 - loss: 11.5529 - val_accuracy: 0.2682 - val_loss: 10.3639
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.4083 - loss: 11.9410 - val_accuracy: 0.6392 - val_loss: 10.8498
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5662 - loss: 12.2662 - val_accuracy: 0.6424 - val_loss: 11.3701
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6221 - loss: 12.6084 - val_accuracy: 0.6410 - val_loss: 11.7711
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6379 - loss: 12.9294 - val_accuracy: 0.6424 - val_loss: 12.2731
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.6407 - loss: 13.4883 - val_accuracy: 0.6401 - val_loss: 12.8075
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6416 - loss: 13.9244 - val_accuracy: 0.6419 - val_loss: 13.2778
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.6427 - loss: 14.3013 - val_accuracy: 0.6415 - val_loss: 13.7376
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6436 - loss: 14.6735 - val_accuracy: 0.6419 - val_loss: 13.9429
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6433 - loss: 15.0679 - val_accuracy: 0.6410 - val_loss: 14.3769
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6439 - loss: 14.4048 - val_accuracy: 0.6422 - val_loss: 13.4013
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6439 - loss: 15.1237 - val_accuracy: 0.6415 - val_loss: 13.9967
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.6440 - loss: 15.4376 - val_accuracy: 0.6419 - val_loss: 14.4674
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6437 - loss: 15.7942 - val_accuracy: 0.6419 - val_loss: 14.9336
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6442 - loss: 16.1560 - val_accuracy: 0.6406 - val_loss: 15.3454
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6437 - loss: 16.5973 - val_accuracy: 0.6420 - val_loss: 15.7985
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6441 - loss: 16.9965 - val_accuracy: 0.6413 - val_loss: 16.2702
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.6438 - loss: 17.6001 - val_accuracy: 0.6417 - val_loss: 16.8396
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.6439 - loss: 18.0275 - val_accuracy: 0.6422 - val_loss: 17.1548
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.6437 - loss: 18.3985 - val_accuracy: 0.6417 - val_loss: 17.5379
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 13s 9ms/step - accuracy: 0.6436 - loss: 18.8175 - val_accuracy: 0.6419 - val_loss: 17.8749
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6441 - loss: 18.9346 - val_accuracy: 0.6415 - val_loss: 18.1093
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6440 - loss: 19.2584 - val_accuracy: 0.6405 - val_loss: 18.0845
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6439 - loss: 19.4812 - val_accuracy: 0.6422 - val_loss: 18.6597
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.6439 - loss: 19.8329 - val_accuracy: 0.6412 - val_loss: 18.8599
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6442 - loss: 20.0552 - val_accuracy: 0.6424 - val_loss: 19.2466
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.6437 - loss: 20.3640 - val_accuracy: 0.6415 - val_loss: 19.4636
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.6439 - loss: 20.6418 - val_accuracy: 0.6419 - val_loss: 19.6282

In [147]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [149]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  HEATHROW  MADRID
True
BASEL        3681         0         1       0
BELGRADE     1092         0         0       0
BUDAPEST      212         1         0       1
DEBILT         82         0         0       0
DUSSELDORF     29         0         0       0
HEATHROW       82         0         0       0
KASSEL         11         0         0       0
LJUBLJANA      60         0         0       1
MAASTRICHT      9         0         0       0
MADRID        456         0         0       2
MUNCHENB        8         0         0       0
OSLO            5         0         0       0
STOCKHOLM       4         0         0       0
VALENTIA        1         0         0       0

#### 11. Adjusting hyperparameters and running model test 4

In [152]:
# Creating the Keras model
epochs = 30
batch_size = 16
n_hidden = 64

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [154]:
# Viewing the model summary
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_3 (LSTM)                   │ (None, 64)             │        18,944 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 15)             │           975 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,919 (77.81 KB)

 Trainable params: 19,919 (77.81 KB)

 Non-trainable params: 0 (0.00 B)

In [156]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [158]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - accuracy: 0.2257 - loss: 11.0593 - val_accuracy: 0.2684 - val_loss: 9.4549
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.3358 - loss: 11.7538 - val_accuracy: 0.6391 - val_loss: 10.4042
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6190 - loss: 12.3741 - val_accuracy: 0.6401 - val_loss: 11.0869
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6424 - loss: 12.5020 - val_accuracy: 0.6420 - val_loss: 11.2374
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6434 - loss: 13.1453 - val_accuracy: 0.6419 - val_loss: 12.1581
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6437 - loss: 13.7882 - val_accuracy: 0.6417 - val_loss: 12.7624
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6437 - loss: 14.3945 - val_accuracy: 0.6424 - val_loss: 13.3996
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6439 - loss: 14.9208 - val_accuracy: 0.6427 - val_loss: 14.2794
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6440 - loss: 15.3566 - val_accuracy: 0.6431 - val_loss: 14.8132
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.6438 - loss: 15.9835 - val_accuracy: 0.6431 - val_loss: 15.3229
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6440 - loss: 16.4999 - val_accuracy: 0.6420 - val_loss: 15.9600
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6436 - loss: 17.0467 - val_accuracy: 0.6412 - val_loss: 16.3479
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6438 - loss: 17.3735 - val_accuracy: 0.6412 - val_loss: 16.6856
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6438 - loss: 17.9780 - val_accuracy: 0.6419 - val_loss: 17.1453
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 14s 13ms/step - accuracy: 0.6441 - loss: 18.5836 - val_accuracy: 0.6413 - val_loss: 17.9067
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 16s 9ms/step - accuracy: 0.6438 - loss: 19.2304 - val_accuracy: 0.6419 - val_loss: 18.3213
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6440 - loss: 19.5808 - val_accuracy: 0.6424 - val_loss: 18.8516
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6440 - loss: 20.0020 - val_accuracy: 0.6415 - val_loss: 19.0710
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6439 - loss: 20.4512 - val_accuracy: 0.6415 - val_loss: 19.6061
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6441 - loss: 21.0350 - val_accuracy: 0.6417 - val_loss: 20.1025
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6440 - loss: 21.3960 - val_accuracy: 0.6426 - val_loss: 20.7245
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.6443 - loss: 21.9311 - val_accuracy: 0.6419 - val_loss: 21.1263
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.6439 - loss: 22.4152 - val_accuracy: 0.6415 - val_loss: 21.5695
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.6438 - loss: 23.1331 - val_accuracy: 0.6422 - val_loss: 22.3152
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6440 - loss: 23.5256 - val_accuracy: 0.6417 - val_loss: 22.6706
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.6439 - loss: 24.0665 - val_accuracy: 0.6420 - val_loss: 22.9526
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6441 - loss: 24.2528 - val_accuracy: 0.6415 - val_loss: 23.4433
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - accuracy: 0.6440 - loss: 24.8975 - val_accuracy: 0.6417 - val_loss: 24.0348
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.6440 - loss: 25.4593 - val_accuracy: 0.6417 - val_loss: 24.2397
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - accuracy: 0.6439 - loss: 25.7185 - val_accuracy: 0.6417 - val_loss: 24.7544

In [160]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [162]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Pred        BASEL  DUSSELDORF
True
BASEL        3682           0
BELGRADE     1091           1
BUDAPEST      214           0
DEBILT         82           0
DUSSELDORF     29           0
HEATHROW       82           0
KASSEL         11           0
LJUBLJANA      61           0
MAASTRICHT      9           0
MADRID        458           0
MUNCHENB        8           0
OSLO            5           0
STOCKHOLM       4           0
VALENTIA        1           0

#### 12. Adjusting hyperparameters and running model test 5

In [165]:
# Creating the Keras model
epochs = 10
batch_size = 16
n_hidden = 8

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [167]:
# Viewing the model summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_4 (LSTM)                   │ (None, 8)              │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │           135 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 711 (2.78 KB)

 Trainable params: 711 (2.78 KB)

 Non-trainable params: 0 (0.00 B)

In [169]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [171]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.0914 - loss: 9.9267 - val_accuracy: 0.0380 - val_loss: 8.9393
Epoch 2/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.1077 - loss: 9.7253 - val_accuracy: 0.0429 - val_loss: 8.7291
Epoch 3/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - accuracy: 0.2297 - loss: 9.4966 - val_accuracy: 0.2625 - val_loss: 8.6456
Epoch 4/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.2745 - loss: 9.4159 - val_accuracy: 0.2487 - val_loss: 8.7244
Epoch 5/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.2801 - loss: 9.4419 - val_accuracy: 0.2558 - val_loss: 8.8405
Epoch 6/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2827 - loss: 9.4940 - val_accuracy: 0.2726 - val_loss: 8.9274
Epoch 7/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.2855 - loss: 9.5825 - val_accuracy: 0.3057 - val_loss: 9.0846
Epoch 8/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.2911 - loss: 9.6929 - val_accuracy: 0.3133 - val_loss: 9.2591
Epoch 9/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.2954 - loss: 9.8625 - val_accuracy: 0.3149 - val_loss: 9.4179
Epoch 10/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.3203 - loss: 9.9720 - val_accuracy: 0.3057 - val_loss: 9.6044

In [173]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [175]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BASEL  BELGRADE  MADRID
True
BASEL        1436         1    2245
BELGRADE      955         0     137
BUDAPEST      194         0      20
DEBILT         82         0       0
DUSSELDORF     27         0       2
HEATHROW       64         0      18
KASSEL         11         0       0
LJUBLJANA      40         0      21
MAASTRICHT      3         0       6
MADRID        140         0     318
MUNCHENB        4         0       4
OSLO            4         0       1
STOCKHOLM       4         0       0
VALENTIA        0         0       1

#### 13. Adjusting hyperparameters and running model test 6

In [178]:
# Creating the Keras model
epochs = 10
batch_size = 16
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [180]:
# Viewing the model summary
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 4)              │           224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 15)             │            75 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 299 (1.17 KB)

 Trainable params: 299 (1.17 KB)

 Non-trainable params: 0 (0.00 B)

In [182]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [184]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.1039 - loss: 8.9905 - val_accuracy: 0.0640 - val_loss: 8.5003
Epoch 2/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.1253 - loss: 8.9967 - val_accuracy: 0.0591 - val_loss: 8.3682
Epoch 3/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.1248 - loss: 8.8908 - val_accuracy: 0.0596 - val_loss: 8.3691
Epoch 4/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 6ms/step - accuracy: 0.1284 - loss: 8.8991 - val_accuracy: 0.0547 - val_loss: 8.4060
Epoch 5/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.1726 - loss: 8.9567 - val_accuracy: 0.2769 - val_loss: 8.4987
Epoch 6/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.1727 - loss: 9.0284 - val_accuracy: 0.2815 - val_loss: 8.5958
Epoch 7/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.2374 - loss: 9.1286 - val_accuracy: 0.3043 - val_loss: 8.6987
Epoch 8/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.2578 - loss: 9.2259 - val_accuracy: 0.3135 - val_loss: 8.8237
Epoch 9/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.2577 - loss: 9.3625 - val_accuracy: 0.3039 - val_loss: 8.9534
Epoch 10/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.2561 - loss: 9.4534 - val_accuracy: 0.3086 - val_loss: 9.1040

In [186]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [188]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BASEL  BELGRADE  MADRID
True
BASEL        1484         2    2196
BELGRADE      962         1     129
BUDAPEST      198         0      16
DEBILT         82         0       0
DUSSELDORF     27         0       2
HEATHROW       69         0      13
KASSEL         11         0       0
LJUBLJANA      48         0      13
MAASTRICHT      4         0       5
MADRID        173         0     285
MUNCHENB        7         0       1
OSLO            4         0       1
STOCKHOLM       4         0       0
VALENTIA        0         0       1

#### 14. Adjusting hyperparameters and running model test 7

In [191]:
# Creating the Keras model
epochs = 10
batch_size = 32
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [193]:
# Viewing the model summary
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_6 (LSTM)                   │ (None, 4)              │           224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │            75 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 299 (1.17 KB)

 Trainable params: 299 (1.17 KB)

 Non-trainable params: 0 (0.00 B)

In [195]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [197]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.2098 - loss: 8.9331 - val_accuracy: 0.1893 - val_loss: 8.3687
Epoch 2/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.1469 - loss: 8.8039 - val_accuracy: 0.1652 - val_loss: 8.3090
Epoch 3/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.1416 - loss: 8.7432 - val_accuracy: 0.1825 - val_loss: 8.2657
Epoch 4/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.1404 - loss: 8.7451 - val_accuracy: 0.2158 - val_loss: 8.2750
Epoch 5/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.1326 - loss: 8.7457 - val_accuracy: 0.2178 - val_loss: 8.2980
Epoch 6/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.1446 - loss: 8.7916 - val_accuracy: 0.2187 - val_loss: 8.3165
Epoch 7/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.1677 - loss: 8.8356 - val_accuracy: 0.2189 - val_loss: 8.3581
Epoch 8/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.1920 - loss: 8.8595 - val_accuracy: 0.2154 - val_loss: 8.4044
Epoch 9/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.1950 - loss: 8.9203 - val_accuracy: 0.3059 - val_loss: 8.4411
Epoch 10/10
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.1814 - loss: 8.9995 - val_accuracy: 0.3116 - val_loss: 8.5005

In [199]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [201]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
Pred        BASEL  BELGRADE  BUDAPEST  MADRID
True
BASEL        1478        29         8    2167
BELGRADE      941        24         9     118
BUDAPEST      195         2         5      12
DEBILT         82         0         0       0
DUSSELDORF     28         0         0       1
HEATHROW       67         0         1      14
KASSEL         11         0         0       0
LJUBLJANA      42         2         0      17
MAASTRICHT      4         0         0       5
MADRID        168         7         6     277
MUNCHENB        7         0         0       1
OSLO            4         0         0       1
STOCKHOLM       4         0         0       0
VALENTIA        0         0         0       1

#### 15. Adjusting hyperparameters and running model test 8

In [204]:
# Creating the Keras model
epochs = 10
batch_size = 8
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [206]:
# Viewing the model summary
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_7 (LSTM)                   │ (None, 4)              │           224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 15)             │            75 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 299 (1.17 KB)

 Trainable params: 299 (1.17 KB)

 Non-trainable params: 0 (0.00 B)

In [208]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [210]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 19s 7ms/step - accuracy: 0.0913 - loss: 8.9848 - val_accuracy: 0.1736 - val_loss: 8.4503
Epoch 2/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - accuracy: 0.1503 - loss: 9.0935 - val_accuracy: 0.1668 - val_loss: 8.6400
Epoch 3/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.2056 - loss: 9.2194 - val_accuracy: 0.3052 - val_loss: 8.9576
Epoch 4/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 22s 7ms/step - accuracy: 0.2437 - loss: 9.5114 - val_accuracy: 0.3088 - val_loss: 9.2837
Epoch 5/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 19s 6ms/step - accuracy: 0.2837 - loss: 9.7733 - val_accuracy: 0.3088 - val_loss: 9.5932
Epoch 6/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 21s 7ms/step - accuracy: 0.2864 - loss: 10.1229 - val_accuracy: 0.3121 - val_loss: 9.9296
Epoch 7/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.2860 - loss: 10.4258 - val_accuracy: 0.3118 - val_loss: 10.2189
Epoch 8/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 22s 7ms/step - accuracy: 0.2868 - loss: 10.7666 - val_accuracy: 0.3146 - val_loss: 10.5014
Epoch 9/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 15s 7ms/step - accuracy: 0.2833 - loss: 11.0520 - val_accuracy: 0.3133 - val_loss: 10.7641
Epoch 10/10
2152/2152 ━━━━━━━━━━━━━━━━━━━━ 14s 7ms/step - accuracy: 0.2964 - loss: 11.3119 - val_accuracy: 0.3137 - val_loss: 11.0587

In [212]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [214]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
Pred        BASEL  MADRID
True
BASEL        1559    2123
BELGRADE     1017      75
BUDAPEST      210       4
DEBILT         82       0
DUSSELDORF     28       1
HEATHROW       74       8
KASSEL         11       0
LJUBLJANA      53       8
MAASTRICHT      6       3
MADRID        217     241
MUNCHENB        7       1
OSLO            4       1
STOCKHOLM       4       0
VALENTIA        0       1

#### 16. Adjusting hyperparameters and running model test 9

In [225]:
# Creating the Keras model
epochs = 10
batch_size = 16
n_hidden = 2

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [227]:
# Viewing the model summary
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_9 (LSTM)                   │ (None, 2)              │            96 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 2)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 15)             │            45 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 141 (564.00 B)

 Trainable params: 141 (564.00 B)

 Non-trainable params: 0 (0.00 B)

In [229]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [231]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.0519 - loss: 8.6238 - val_accuracy: 0.0739 - val_loss: 8.1777
Epoch 2/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0628 - loss: 8.5509 - val_accuracy: 0.0547 - val_loss: 8.1704
Epoch 3/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - accuracy: 0.0614 - loss: 8.5815 - val_accuracy: 0.0732 - val_loss: 8.1960
Epoch 4/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0616 - loss: 8.6272 - val_accuracy: 0.0777 - val_loss: 8.2435
Epoch 5/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0627 - loss: 8.6817 - val_accuracy: 0.0791 - val_loss: 8.2920
Epoch 6/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.0779 - loss: 8.7561 - val_accuracy: 0.0796 - val_loss: 8.3388
Epoch 7/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.1630 - loss: 8.8029 - val_accuracy: 0.0796 - val_loss: 8.4004
Epoch 8/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.1795 - loss: 8.8863 - val_accuracy: 0.0798 - val_loss: 8.4588
Epoch 9/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.1760 - loss: 8.9569 - val_accuracy: 0.2004 - val_loss: 8.5323
Epoch 10/10
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.1784 - loss: 9.0121 - val_accuracy: 0.3027 - val_loss: 8.5731

In [233]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [235]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  BUDAPEST  HEATHROW  MADRID
True
BASEL        1438        23         3         1    2217
BELGRADE      872        28         1         0     191
BUDAPEST      188         2         0         0      24
DEBILT         82         0         0         0       0
DUSSELDORF     26         1         0         0       2
HEATHROW       73         1         0         0       8
KASSEL         11         0         0         0       0
LJUBLJANA      38         4         1         0      18
MAASTRICHT      5         0         0         0       4
MADRID        165        17         1         0     275
MUNCHENB        5         1         0         0       2
OSLO            5         0         0         0       0
STOCKHOLM       4         0         0         0       0
VALENTIA        1         0         0         0       0

#### 17. Adjusting hyperparameters and running model test 10

In [262]:
# Creating the Keras model
epochs = 15
batch_size = 32
n_hidden = 8

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [264]:
# Viewing the model summary
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_13 (LSTM)                  │ (None, 8)              │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_13 (Dropout)            │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 15)             │           135 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 711 (2.78 KB)

 Trainable params: 711 (2.78 KB)

 Non-trainable params: 0 (0.00 B)

In [266]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [268]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.1400 - loss: 9.5935 - val_accuracy: 0.0347 - val_loss: 8.8205
Epoch 2/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.0898 - loss: 9.6803 - val_accuracy: 0.1811 - val_loss: 8.5841
Epoch 3/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.1050 - loss: 9.4701 - val_accuracy: 0.1739 - val_loss: 8.4783
Epoch 4/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.1568 - loss: 9.3668 - val_accuracy: 0.2124 - val_loss: 8.4286
Epoch 5/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.1962 - loss: 9.3193 - val_accuracy: 0.3079 - val_loss: 8.4268
Epoch 6/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2367 - loss: 9.3031 - val_accuracy: 0.3090 - val_loss: 8.4479
Epoch 7/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2458 - loss: 9.3036 - val_accuracy: 0.3113 - val_loss: 8.4880
Epoch 8/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.2719 - loss: 9.3453 - val_accuracy: 0.3102 - val_loss: 8.5409
Epoch 9/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.2658 - loss: 9.3886 - val_accuracy: 0.3057 - val_loss: 8.5972
Epoch 10/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2655 - loss: 9.4290 - val_accuracy: 0.3072 - val_loss: 8.6783
Epoch 11/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2687 - loss: 9.5025 - val_accuracy: 0.3053 - val_loss: 8.7474
Epoch 12/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.2721 - loss: 9.5415 - val_accuracy: 0.3066 - val_loss: 8.8122
Epoch 13/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 8ms/step - accuracy: 0.2784 - loss: 9.6055 - val_accuracy: 0.3095 - val_loss: 8.8781
Epoch 14/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.2779 - loss: 9.6597 - val_accuracy: 0.3104 - val_loss: 8.9668
Epoch 15/15
538/538 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.2840 - loss: 9.7530 - val_accuracy: 0.3113 - val_loss: 9.0470

In [270]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [272]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  LJUBLJANA  MADRID  STOCKHOLM
True
BASEL        1537         3          0    2141          1
BELGRADE     1019         1          0      72          0
BUDAPEST      211         0          0       3          0
DEBILT         82         0          0       0          0
DUSSELDORF     28         0          0       1          0
HEATHROW       73         1          0       8          0
KASSEL         11         0          0       0          0
LJUBLJANA      52         0          0       9          0
MAASTRICHT      5         0          0       4          0
MADRID        207         1          2     248          0
MUNCHENB        7         0          0       1          0
OSLO            4         0          0       1          0
STOCKHOLM       4         0          0       0          0
VALENTIA        1         0          0       0          0

#### 18. Adjusting hyperparameters and running model test 11

In [301]:
# Creating the Keras model
epochs = 15
batch_size = 64
n_hidden = 8

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [303]:
# Viewing the model summary
model.summary()

Model: "sequential_17"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_17 (LSTM)                  │ (None, 8)              │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 8)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 15)             │           135 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 711 (2.78 KB)

 Trainable params: 711 (2.78 KB)

 Non-trainable params: 0 (0.00 B)

In [305]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [307]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.1207 - loss: 9.4369 - val_accuracy: 0.2537 - val_loss: 9.0547
Epoch 2/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1357 - loss: 10.1137 - val_accuracy: 0.2708 - val_loss: 9.3507
Epoch 3/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1350 - loss: 10.2744 - val_accuracy: 0.2682 - val_loss: 9.1832
Epoch 4/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1394 - loss: 10.0939 - val_accuracy: 0.2583 - val_loss: 9.0254
Epoch 5/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1437 - loss: 9.9396 - val_accuracy: 0.2689 - val_loss: 8.9071
Epoch 6/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1583 - loss: 9.8256 - val_accuracy: 0.2691 - val_loss: 8.8136
Epoch 7/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1781 - loss: 9.7629 - val_accuracy: 0.2652 - val_loss: 8.7523
Epoch 8/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2049 - loss: 9.6924 - val_accuracy: 0.2621 - val_loss: 8.6965
Epoch 9/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.2086 - loss: 9.6252 - val_accuracy: 0.2637 - val_loss: 8.6611
Epoch 10/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.2370 - loss: 9.5957 - val_accuracy: 0.2703 - val_loss: 8.6258
Epoch 11/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.2394 - loss: 9.5578 - val_accuracy: 0.2548 - val_loss: 8.6388
Epoch 12/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.2422 - loss: 9.5401 - val_accuracy: 0.2598 - val_loss: 8.5954
Epoch 13/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2455 - loss: 9.5397 - val_accuracy: 0.2635 - val_loss: 8.5816
Epoch 14/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2596 - loss: 9.5097 - val_accuracy: 0.2675 - val_loss: 8.5660
Epoch 15/15
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2587 - loss: 9.5074 - val_accuracy: 0.2623 - val_loss: 8.5727

In [309]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [311]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BUDAPEST  DEBILT  DUSSELDORF  HEATHROW  MAASTRICHT  MADRID  \
True
BASEL        1491         2       0        2151         3           6      19
BELGRADE     1009         0       0          64         2           1      15
BUDAPEST      206         0       0           3         0           0       5
DEBILT         82         0       0           0         0           0       0
DUSSELDORF     27         0       0           1         0           0       1
HEATHROW       70         1       1           7         0           2       1
KASSEL         11         0       0           0         0           0       0
LJUBLJANA      49         0       0           7         1           0       3
MAASTRICHT      4         0       0           4         1           0       0
MADRID        174         1       3         257         0           7      13
MUNCHENB        7         0       0           1         0           0       0
OSLO            4         0       0           1         0           0       0
STOCKHOLM       4         0       0           0         0           0       0
VALENTIA        0         0       0           0         0           1       0

Pred        MUNCHENB  STOCKHOLM
True
BASEL              2          8
BELGRADE           0          1
BUDAPEST           0          0
DEBILT             0          0
DUSSELDORF         0          0
HEATHROW           0          0
KASSEL             0          0
LJUBLJANA          0          1
MAASTRICHT         0          0
MADRID             1          2
MUNCHENB           0          0
OSLO               0          0
STOCKHOLM          0          0
VALENTIA           0          0

#### 19. Adjusting hyperparameters and running model test 12

In [330]:
# Creating the Keras model
epochs = 30
batch_size = 80
n_hidden = 4

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.5))
model.add(Dense(n_classes, activation='sigmoid'))

In [332]:
# Viewing the model summary
model.summary()

Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_20 (LSTM)                  │ (None, 4)              │           224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 15)             │            75 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 299 (1.17 KB)

 Trainable params: 299 (1.17 KB)

 Non-trainable params: 0 (0.00 B)

In [334]:
# Compiling the model
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [336]:
# Fitting the model
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - accuracy: 0.0431 - loss: 9.0142 - val_accuracy: 0.0232 - val_loss: 8.4006
Epoch 2/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.0541 - loss: 9.0064 - val_accuracy: 0.0399 - val_loss: 8.3437
Epoch 3/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.0512 - loss: 8.9672 - val_accuracy: 0.0422 - val_loss: 8.3203
Epoch 4/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0532 - loss: 8.9410 - val_accuracy: 0.0491 - val_loss: 8.3049
Epoch 5/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0546 - loss: 8.9283 - val_accuracy: 0.1663 - val_loss: 8.3002
Epoch 6/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0713 - loss: 8.9123 - val_accuracy: 0.1750 - val_loss: 8.2740
Epoch 7/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0887 - loss: 8.8933 - val_accuracy: 0.1713 - val_loss: 8.2730
Epoch 8/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.0992 - loss: 8.8851 - val_accuracy: 0.1697 - val_loss: 8.2701
Epoch 9/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.0982 - loss: 8.8927 - val_accuracy: 0.1678 - val_loss: 8.2664
Epoch 10/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.0938 - loss: 8.8770 - val_accuracy: 0.1643 - val_loss: 8.2650
Epoch 11/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.0978 - loss: 8.8787 - val_accuracy: 0.1720 - val_loss: 8.2542
Epoch 12/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1049 - loss: 8.8583 - val_accuracy: 0.1795 - val_loss: 8.2458
Epoch 13/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1124 - loss: 8.8563 - val_accuracy: 0.1720 - val_loss: 8.2494
Epoch 14/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.1122 - loss: 8.8431 - val_accuracy: 0.1724 - val_loss: 8.2489
Epoch 15/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1134 - loss: 8.8448 - val_accuracy: 0.1671 - val_loss: 8.2526
Epoch 16/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1276 - loss: 8.8518 - val_accuracy: 0.1751 - val_loss: 8.2470
Epoch 17/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.1781 - loss: 8.8454 - val_accuracy: 0.1605 - val_loss: 8.2606
Epoch 18/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1813 - loss: 8.8545 - val_accuracy: 0.1628 - val_loss: 8.2539
Epoch 19/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.1820 - loss: 8.8379 - val_accuracy: 0.0481 - val_loss: 8.2583
Epoch 20/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1772 - loss: 8.8372 - val_accuracy: 0.2677 - val_loss: 8.2588
Epoch 21/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1855 - loss: 8.8400 - val_accuracy: 0.2623 - val_loss: 8.2645
Epoch 22/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1771 - loss: 8.8395 - val_accuracy: 0.2633 - val_loss: 8.2642
Epoch 23/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.1816 - loss: 8.8424 - val_accuracy: 0.2649 - val_loss: 8.2737
Epoch 24/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1816 - loss: 8.8472 - val_accuracy: 0.3081 - val_loss: 8.2744
Epoch 25/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.1945 - loss: 8.8643 - val_accuracy: 0.3085 - val_loss: 8.2755
Epoch 26/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.1948 - loss: 8.8733 - val_accuracy: 0.3100 - val_loss: 8.2796
Epoch 27/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2108 - loss: 8.8546 - val_accuracy: 0.3078 - val_loss: 8.2893
Epoch 28/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2428 - loss: 8.8586 - val_accuracy: 0.3076 - val_loss: 8.2928
Epoch 29/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2483 - loss: 8.8715 - val_accuracy: 0.3085 - val_loss: 8.3011
Epoch 30/30
216/216 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.2544 - loss: 8.8765 - val_accuracy: 0.3057 - val_loss: 8.3156

In [338]:
# Creating a confusion matrix
def confusion_matrix(y_true, y_pred):
    y_true = pd.Series([stations[y] for y in np.argmax(y_true, axis=1)])
    y_pred = pd.Series([stations[y] for y in np.argmax(y_pred, axis=1)])

    return pd.crosstab(y_true, y_pred, rownames=['True'], colnames=['Pred'])

In [340]:
# Printing the confusion matrix
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  BUDAPEST  LJUBLJANA  MADRID  MUNCHENB  OSLO
True
BASEL        1416         1         0          2    2262         1     0
BELGRADE      917         1         2          1     171         0     0
BUDAPEST      190         0         0          0      24         0     0
DEBILT         82         0         0          0       0         0     0
DUSSELDORF     25         0         0          0       4         0     0
HEATHROW       56         1         0          0      25         0     0
KASSEL         10         0         0          0       1         0     0
LJUBLJANA      36         1         1          0      21         0     2
MAASTRICHT      3         0         0          0       6         0     0
MADRID        118         0         2          0     338         0     0
MUNCHENB        5         0         0          0       3         0     0
OSLO            4         0         0          0       1         0     0
STOCKHOLM       4         0         0          0       0         0     0
VALENTIA        0         0         0          0       1         0     0